### ISSUE TITLE
Notes/HTML Primer/Page Structure/ Video does not work

### ISSUE THREAD

**Issue by harrison2705** [susanBuck/e2-fall21#10]
Hi Susan, 

The **Page structure** video does not work for me (screenshot attached). Could you please update the link? 

Many thanks.

Link to the page: https://hesweb.dev/e2/notes/html-primer/page-structure

Screenshot: 
![Screen Shot 2021-09-03 at 2 26 14 pm](https://user-images.githubusercontent.com/51356896/131950672-eb9d43cb-fb8e-41ea-a07e-dcbb9b0f0769.png)

**Comment by susanBuck** [comment]
Just corrected; thanks for drawing this to my attention.
