### ISSUE TITLE
Hello There!

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#11]
I would like to introduce my self as a new student in the E2-Fall21. 

My name is **Murthy Garimella**, I live in *Colorado*. If you would like to know more about Colorado, please check out the tourism site for [Colorado...](https://www.colorado.com)

As a part of this course, I would like to share a small snippet of html code -
```html
<h1>
Hello World!
</h1>
```

My favorite technologies include:
+ php
+ python
+ linux

**Comment by susanBuck** [comment]
Good Markdown practice. : )

**Comment by mgarimelHES** [comment]
Thank you **Susan!**
