### ISSUE TITLE
typing.io: Typing Practice for Programmers

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#12]
Hi everyone -

A past student shared this neat web app with me, and I wanted to pass it on: https://typing.io

It allows you to practice typing all the awkward characters that are a part of code. I like to share this in my intro course because it's something I see new programmers struggle with - code is so particular and involves so many characters we don't use in regular "every day" language. This trips beginners up for two reasons:

1. They make little mistakes with the characters and it prevents their code from working as expected
2. The characters slow down how fast they can type, and then coding feels awkward, and as a result, frustrating

The above two points all smooth out with experience, but spending a little bit of time each day with typing.io can help expedite that process.

If you want to try it out, here's there PHP example you can work with: https://typing.io/lesson/php/symfony/PhpEngine.php/1

**Comment by mgarimelHES** [comment]
I am wondering if VScode has this extension or similar to help later on? Thanks.

**Comment by susanBuck** [comment]
@mgarimelHES Not that I'm aware of.
