### ISSUE TITLE
Root access, increasing server security

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#14]
Hi everyone,

In this week's videos we set up servers and log into them as a default **root** user. In one of the videos I explain how this is fine for this course/learning purposes, but in a ”real world” context, for security reasons it'd be wise to create a separate user you primarily operate as.

To elaborate on that, I've published a supplemental set of notes: [Appendix > Increasing server security](https://hesweb.dev/e2/notes/appendix/increasing-server-security).

These notes are optional and it's not required you implement the steps outlined. In fact, if you're new to working with servers, it might be best to explore these steps after the course is over, just to keep things simpler.

If you do decide to implement what is in these notes and run into any problems, don't hesitate to ask any questions here in the forum.

**Comment by syedyasirkamal** [comment]
Just out of curiosity since I have never dealt with back end stuff before... 

These multitude of steps code and commands for setting up, connecting to server and github

Are we expected in this course to be able to do this without referring to notes/videos? Also in real world, do people reall know how to do this stuff by knowledge or do they have to follow some manual as a reference? It felt a little overwhelming and some of it was just beyond comprehension.

**Comment by susanBuck** [comment]
100% you should rely on notes/reference. I've been working with this stuff for years and I still refer to my own notes (as well as outside notes) on these procedures as needed.

It's part of the reason I try and emphasize notes/resources so much in this course. There too much information we need to know to try and commit everything to memory.

Are there specific parts that were beyond comprehension that I could help elaborate on?

**Comment by syedyasirkamal** [comment]
As you mentioned in the lecture , it was just a lot of stuff to digest especially for newbies liike myself

I got the gist of what we were trying to achieve... its just the gazillion commands we were writing which were difficult to keep a track of or grasp like the things we did to setup git or create subdomains in the terminal

I just kept following what you were doing and was able to complete the steps successfully.

**Comment by susanBuck** [comment]
@syedyasirkamal Gotcha. Getting the gist of what we were trying to achieve and getting it working were two main goals, so you're right on track. 👍 

The details will start to make sense the more time you spend with this stuff. A trick I like to employ when I'm overwhelmed with something new is to jot down things/questions that I don't understand yet as I go along. It lets my mind unload a bit, allowing me to proceed forward. Then, I can always double back on those notes as I have more time and start to understand things more.

**Comment by owen-mcg** [comment]
@syedyasirkamal My guess is that the folks who know this stuff 100% from memory are like sys admins and linux/unix devs, people who work in command line hours per day. It's a lot lol.
