### ISSUE TITLE
Cross platform development with Windows & Mac

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#15]
Hi **Susan**,

 Is it ok if I do my class work across multiple OSes since sometimes I may use my Mac or WIndows depending on my nature of regular work.

In this case, I am assuming since I have all the pre-requisites on my laptops and working on remote development server, it should not matter, just want to make sure.

Thanks,

**Comment by susanBuck** [comment]
Yup, this is one of the advantages of remote development. :-)

To give a "new" computer access to your server you want to generate a SSH key pair on that computer, and add the public key into the file `~/.ssh/authorized_keys` on the server.

To do this requires getting the public key from the "new" computer to the existing computer that already has access to the server. A secure way to you can transfer the key is paste it into https://onetimesecret.com/ and email it to yourself so you can access it from the computer that has access to the server and can edit the authorized_key file.

Another option to do it all from the "new" computer is to access the server via DigitalOcean's console access. You'll find this under your Droplet settings. So you'd generate the key pair, access the server via the console, edit the authorized_key file to add the key. Then you should have SSH access from the "new" computer.

If you set things up and have any questions along the way, let me know.

**Comment by mgarimelHES** [comment]
Thank you so much, it helps a lot. Appreciate it.
