### ISSUE TITLE
Week 3 bonus content: Customizing command line

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#18]
Hi everyone,

There's been a couple posts that have talked about customizing your command line prompt so I wanted to share some resources on how to do this for those that were curious. In addition to customizing the prompt, I also share how to create aliases for commonly used commands.

**This content is optional.**

+ Notes: [Appendix > Customizing CL](https://hesweb.dev/e2/notes/appendix/customizing-cl)
+ Video: [e2 Week 3 bonus video: Customizing CL](https://www.youtube.com/embed/NZFSOkmD4ps?rel=0&showinfo=0)

Relevant posts:
+ https://github.com/susanBuck/e2-fall21/issues/17
+ https://github.com/susanBuck/e2-fall21/issues/9

**Comment by owen-mcg** [comment]
Thanks for creating this content; I'm definitely going to check it out. Command line always makes me feel like a hacker in a 90s movie. It's a pretty great feeling.

**Comment by susanBuck** [comment]
@owen-mcg Agreed. CL feels clunky at first but once you get the hang of it it's kind of fun to work with. : )
