### ISSUE TITLE
FYI: Week 1 Assignment grades released; questionnaire data

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#19]
Hi everyone,

Just a quick announcement that I've released the Week 1 Assignment grades. You should be able to view the assignment in Canvas and see your score, the correct answers, and any comments I left for you. 

As noted in a previous lecture, assignment grades are always released the day after their final submission cut-off, so this means that moving forward you'll be seeing grades/feedback every Wednesday by midnight. 

I won't typically make an announcement like this when grades are released, but you should get a notification from Canvas.

If you have any questions/concerns about your grades, don't hesitate to drop me an email at susanbuck@fas.harvard.edu.

## Questionnaire data
For those that are curious, here's some of the data collected from the start of semester questionnaire.

![image](https://user-images.githubusercontent.com/237711/133457667-786f1d3d-4a6c-43ce-b314-b498c45f591c.png)
![image](https://user-images.githubusercontent.com/237711/133457828-98595233-04d9-476d-84af-525254d657a4.png)
![image](https://user-images.githubusercontent.com/237711/133457934-bf40a069-4089-40b1-b0d6-03538c388f3c.png)

![image](https://user-images.githubusercontent.com/237711/133459953-8c623e49-d3bc-42d2-ba1c-805c37d32524.png)
1 - It's new to me
2 - I'm familiar with it, but don't have a lot of experience with it
3 - I'm comfortable with it

![image](https://user-images.githubusercontent.com/237711/133460161-e4b4244b-7584-4e91-884f-687a893d6149.png)
1 - It's new to me
2 - I'm familiar with it, but don't have a lot of experience with it
3 - I'm comfortable with it

![image](https://user-images.githubusercontent.com/237711/133460312-774b327d-5c31-4073-89e8-e111b6c4b419.png)
1 - It's new to me, so I learned about it in preparation of this course
2 - I'm familiar with it, but don't have a lot of experience with it
3 - I'm comfortable with it

**Comment by mgarimelHES** [comment]
Hi **Susan**,

 Thanks for the information provided, I am wondering if we get any kind of report moving forward on overall class performance similar to the dashboard above?

Regards,

./mg

**Comment by owen-mcg** [comment]
This is really interesting, @susanBuck, thanks for sharing this.

**Comment by susanBuck** [comment]
@mgarimelHES Because the course isn't graded on any sort of curve, I don't find that information necessary/worth taking the time to compile each week. If you have concerns about your individual performance, shoot me an email.

**Comment by mgarimelHES** [comment]
Thanks **Susan**

**Comment by ngal2021** [comment]
Very interesting to see the data. I wonder how different these metrics will look at the end of the semester. I think the experience graphs would change a lot!
