### ISSUE TITLE
Q - Is there any know issue with DigitalOcean server, facing very slow connection

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#20]
Hello **Friends**,

I am not sure if it is on my end or something impacting some of you as well?

I am facing a slow connectivity to *DigitalOcean* server today and it is very slow from VS Code to make a remote dev server connection and looks like it is keep 'reconnecting to SSH: hes-on-DigitalOcean'.

Thanks for any pointers,

Murthy

**Comment by owen-mcg** [comment]
I've experienced this a bit as well. For me, I had just let my connection lapse about 10 times in a row, so I'm guessing it was kind of user error there; I quit vs code completely and opened it up again and that seemed to get it straight. But it does sound like a different circumstance. Sounds frustrating! Hope you get it solved.

**Comment by susanBuck** [comment]
@mgarimelHES I haven't observed any slowness on my end.

I don't see any status issues within the last couple days: https://status.digitalocean.com.

**Comment by mgarimelHES** [comment]
Hi **Owen-mcg** and **Susan** for your response and help. It is ok for now, I hope it could be some network issue and it might be resolved.

Appreciate your help.

**Comment by mgarimelHES** [comment]
Hello,

 I am running into the same issue, I am not able to connect to the remote server, any pointers please. I need to submit my project2 in few hours.

Thanks

**Comment by susanBuck** [comment]
@mgarimelHES - Try logging into DigitalOcean and restarting your server. You'll do that via the green toggle button when looking at your server settings. For example:

![image](https://user-images.githubusercontent.com/237711/138974870-b265d968-6253-4d2d-ba82-b7dff1782385.png)
