### ISSUE TITLE
Mitigating 404 Not Found error for bank.php

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#21]
I am getting a _**404 Not Found**_ error when I try to load my bank.php file on my server, and I am having trouble finding a solution.

### Mitigating the problem
Here are the steps I have taken to try to solve the problem and some things I have noticed.

**1. URL:** I think I've written the subdomain, domain, and file name correctly: http://e2practice.nicolaphp.me/bank.php 
**2. Folder structure:** The folder structure seems to be okay: e2/practice
**3. Syntax:** Copied/pasted from the notes - I haven't gotten to the stage of editing it yet, so there shouldn't be an error there.
**4. Saving my file:** I've saved my file, however, I have not synchronized my changes with GitHub.
**5. Another file isn't updating:** I noticed that my index.php file is showing a previous version of the file (page that reads, "Hello from my DigitalOcean server!") instead of what is currently in the file, which is a heading that reads "Practice App" and the HES logo.

### Screenshot of my VS Code and browser
VS Code on the left shows the folder structure, bank.php file, and that I am connected to the Digital Oceans server. The browser on the right shows the URL and the **_404 Not Found_** error.

![Screen Shot 2021-09-20 at 8 16 03 PM](https://user-images.githubusercontent.com/86396684/134093607-380cfff0-2aa4-4512-b696-9b30b5f7c970.png)

Appreciative of the support with this!

**Comment by susanBuck** [comment]
Hi @ngal2021 -

Can you share the contents of the file `/etc/nginx/sites-available/hes` so we can double check your subdomain configurations?

**Comment by ngal2021** [comment]
@susanBuck yes, I can! But, I am having a bit of trouble finding the file. I've done a few things to try to find it.

Looking through Digital Ocean files (I also looked on the online Dashboard)
![Screen Shot 2021-09-20 at 9 03 54 PM](https://user-images.githubusercontent.com/86396684/134096973-fff182b1-fd62-4c9e-b154-40989be16048.png)

I looked on my Namecheap dashboard (Domain List > Advanced DNS). Is it the file associated with the CNAME Record?
![Screen Shot 2021-09-20 at 8 59 17 PM](https://user-images.githubusercontent.com/86396684/134096736-a56738d9-69b8-4068-8897-e0fcca853e35.png)

I also tried to ran the command in my virtual terminal, which seems very wrong:
![Screen Shot 2021-09-20 at 8 55 05 PM](https://user-images.githubusercontent.com/86396684/134096465-5d3d015e-e103-4f0e-bce0-ec53eff4e4a3.png)

**Comment by susanBuck** [comment]
Try this command:

```
$ code /etc/nginx/sites-available/hes
```

That should open the file directly in VSCode (just like we did when [setting up the subdomain](https://hesweb.dev/e2/notes/infrastructure/subdomains#subdomains))

If that doesn't do the trick, let me know!

**Comment by ngal2021** [comment]
@susanBuck it worked! thank you. Below is a screenshot of the code - it looks like I left it configured for my project 1 folder.

![Screen Shot 2021-09-20 at 9 19 29 PM](https://user-images.githubusercontent.com/86396684/134097972-f64b849f-1069-469c-a002-a83231244847.png)

To reconfigure it, should I replace **p1** with **practice**? Here is an example of **revised lines 1-4**:
```
server {
    listen 80;
    server_name e2practice.nicolaphp.me;
    root /var/www/e2/practice/;
```

**Comment by susanBuck** [comment]
You should leave your existing e2p1 config as is - that is working fine: http://e2p1.nicolaphp.me 👍

What you want to do is add a **separate** configuration block for the e2practice subdomain

Below is an example showing how my configs are set up...

Note there's the first block (starting with `server {` and ending with `}`) for the _e2practice_ subdomain...
Followed by the second block (again starting with `server {` and ending with `}`) for the _e2p1_ subdomain


```xml
server {
    listen 80;
    server_name e2practice.hesweb.xyz;
    root /var/www/e2/practice/;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

server {
    listen 80;
    server_name e2p1.hesweb.xyz;
    root /var/www/e2/p1/;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

What we're doing is **configuring multiple subdomains in the same config file**.

Get your file looking similar to mine (replacing `hesweb.xyz` with your domain in the two places it appears), and I think you should be good to go after restarting nginx (`systemctl restart nginx`).

If not, share the contents of your hes file again and I'll give it a second set of eyes. : )

**Comment by ngal2021** [comment]
@susanBuck It works! I see the piggy bank when I load the bank.php file, and all my other files are also updating/working correctly. It makes a lot of sense to configure multiple subdomains in the same config file - that was something that I didn't fully understand last week! Very helpful to put it into practice.

Appreciative of your support! 
-Nicola

**Comment by susanBuck** [comment]
Excellent, http://e2practice.nicolaphp.me/bank.php looks good on my end as well! :)

Circling back a little bit now that we resolved the problem, a note/tip:

Above, when trying to open `/etc/nginx/sites-available/hes` you received a "permission denied" error because you didn't prefix the path with any command. 

![image](https://user-images.githubusercontent.com/237711/134099833-09144911-04dc-4656-b499-70d6da2dbc2b.png)

When you ran simply `/etc/nginx/sites-available/hes`, command line interpreted it as if you were trying to run `/etc/nginx/sites-available/hes` as a command itself, which is not possible (hence the "permission denied" error).

Instead, you want to have some sort of command before the path. For example, the `cat` command would output the contents of the file:

```bash
$ cat /etc/nginx/sites-available/hes 
```

Or - as we saw, you can use the `code` command to open the file via VSCode:

```bash
$ code /etc/nginx/sites-available/hes
```

Thought I would elaborate on this because I think when we understand why something didn't work as expected, it can help us better remember the correct to do something moving forward. : )

**Comment by ngal2021** [comment]
@susanBuck definitely! The elaboration is very helpful for clarity. I need to tell my computer to do something with the file at the certain path, not just tell my computer what the path is. 

I've added the commands to my _Command Line quick reference_ print out. Thanks again!

**Comment by susanBuck** [comment]
> I need to tell my computer to do something with the file at the certain path, not just tell my computer what the path is.

Perfect explanation! 👍

Going to close out this issue since things are resolved, but don't hesitate to create another post if you hit any more road blocks.
