### ISSUE TITLE
Q - Week4 For loop example

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#23]
I think the examples for 'for' loop results in more than 10 due to <= condition (0 - 10, i.e. 11), is it good to have '<' condition as shown in the recording to limit only 10 ?

**Comment by susanBuck** [comment]
Hi @mgarimelHES - I'm not sure I understand your question. 

Can you clarify what you're referring to?

**Comment by mgarimelHES** [comment]
Hi **Susan**,

Sorry about the confusion, it is resolved after comparing the *notes* with the *video recording*

Thanks
