### ISSUE TITLE
Frequent but irregular HTTP ERROR 404 when working along with lecture... 

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#24]
I often have trouble seeing my pages when I am following along with the lectures. Sometimes the pages do not display, and then they do. I have tried clearing the cache, and opening up the link in an incognito window. Sometimes that seems to help, but sometimes it does not. 
I am wondering if there is something that I am missing. Does anyone have a solution?

**I expect to see this:**
![Screen Shot 2021-09-24 at 4 16 07 PM](https://user-images.githubusercontent.com/77531411/134735845-f3a42edb-14f2-41e3-93c2-49d5442da061.png)
**But I often see this:**
![Screen Shot 2021-09-24 at 4 29 25 PM](https://user-images.githubusercontent.com/77531411/134736034-e8c79516-93c5-46ec-8f8d-e0117de8c1a2.png)
I am attaching a link to a video in which I demonstrate the problem. 
[2 Minute Video Explanation of issue and attempts to solve it](https://youtu.be/8hxWtss8kmw)

**Comment by susanBuck** [comment]
@mike32jacobs Thanks for such a clear/detailed explanation of the problem.

Can you share a screenshot of your DNS settings?

I've seen something similar happen when a student had a domain with two "A" records in their DNS settings - one was pointing to one IP address and the other was pointing to another. It caused erratic behavior like you're describing because sometimes visiting the address would resolve to the one IP, and other times it'd resolve to the other.

I just "pinged" your domain from command line and in the first response it resolved to the IP address `143.244.155.122` (which appears to be your functioning DigitalOcean IP)... but then a few moments later it resolved to `162.255.119.33` (which is not functioning). 

```bash
/Users/Susan  $ ping nhroyal.com
PING nhroyal.com (143.244.155.122): 56 data bytes
64 bytes from 143.244.155.122: icmp_seq=0 ttl=50 time=48.986 ms
64 bytes from 143.244.155.122: icmp_seq=1 ttl=50 time=63.653 ms

--- nhroyal.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 48.986/56.319/63.653/7.333 ms
/Users/Susan  $ ping nhroyal.com
PING nhroyal.com (162.255.119.33): 56 data bytes
64 bytes from 162.255.119.33: icmp_seq=0 ttl=45 time=249.628 ms

--- nhroyal.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 249.628/249.628/249.628/0.000 ms
/Users/Susan  $ 
```

**Comment by mike32jacobs** [comment]
Is this what you need? 
<img width="998" alt="Screen Shot 2021-09-25 at 6 20 57 AM" src="https://user-images.githubusercontent.com/77531411/134768074-4551d054-0a28-4109-ad87-2db40abd0825.png">
When I "pinged" the domain, I got the same results. Last night I was getting the 143.244.155.122, and this morning I got 162.255.119.33.

`64 bytes from 143.244.155.122: icmp_seq=15 ttl=50 time=31.183 ms
^C
--- nhroyal.com ping statistics ---
16 packets transmitted, 16 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 22.220/29.684/40.332/4.919 ms`

and
`64 bytes from 162.255.119.33: icmp_seq=4 ttl=49 time=100.102 ms
^C
--- nhroyal.com ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 92.333/97.795/103.247/4.173 ms`

**Comment by susanBuck** [comment]
Yup, that's what I was looking for. 

Try deleting the _"URL Redirect Record"_ record (third one on the list). That looks like it'd cause a loop - it's saying any traffic to nhyroyal.com should get directed to nhroyal.com. 

I also suspect that "under the hood" Namecheap is making that _"URL Redirect Record"_ via an "A" record. Check out these details from this DNS lookup tool:

![image](https://user-images.githubusercontent.com/237711/134773078-e99da304-82ad-420b-83d8-49337ae953a3.png)

It's definitely seeing two A records for your domain. The first one is to the nonfunctioning IP which we can see from this output is resolving to Namecheap's servers. I bet that's coming from the "URL Redirect Record".

So, go ahead and delete that record and we can see where it gets us.

**Comment by susanBuck** [comment]
For reference, here's the tool I used in the above post: https://mxtoolbox.com/SuperTool.aspx?action=a%3anhroyal.com&run=toolpage

**Comment by mike32jacobs** [comment]
Thanks for your help. That appears to have worked.
