### ISSUE TITLE
Output with line break using var_dump

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#25]
I notice that your output looks like this:
![Screen Shot 2021-09-26 at 7 50 44 AM](https://user-images.githubusercontent.com/77531411/134806639-13f17928-63c0-4359-a13c-38b608a10a1d.png)
My output looks like this:
![Screen Shot 2021-09-26 at 7 51 07 AM](https://user-images.githubusercontent.com/77531411/134806655-b901bcf8-dfdd-4f7f-870d-1c64ccd2b9c9.png)

The line breaks make it more readable. (My apologies if I missed this concept in a previous post.) Is there a way to include the line breaks in the var_dump output?

**Comment by susanBuck** [comment]
Hi @mike32jacobs - In the [Week 4, Part 2 video](https://www.youtube.com/embed/XyQBQmF6Cc0?rel=0&showinfo=0) at about the 10:50 mark I show how to get that output. Let me know if you have any problems finding the "View Source" option in your browser of choice.

**Comment by mike32jacobs** [comment]
Thanks again for the help. Sorry for the repetition.

**Comment by susanBuck** [comment]
No worries - lots of details in the lectures so it's understandable to miss a point here and there. : )
