### ISSUE TITLE
Conditionals; Rock, Paper, Scissors

### ISSUE THREAD

**Issue by owen-mcg** [susanBuck/e2-fall21#27]
I was wondering as I'm re-watching conditionals: would it be possible to create variables or functions of rock and paper and scissors and compare them against each other? like $rock > $scissors, $scissors > $paper; etc.

**Comment by susanBuck** [comment]
Yes, but it gets a bit complex. 

Here's a great write-up on how to do it: https://therenegadecoder.com/code/rock-paper-scissors-using-modular-arithmetic/

That article is not written with PHP, but the basic logic/formula would still apply. After the Project 1 deadline passes, I'll share a version written in PHP for those that are curious. : )

**Comment by owen-mcg** [comment]
Nice! Yeah I'm very interested. Would this be more like object oriented paradigm, where the rock, paper, and scissors would each be an object?

**Comment by susanBuck** [comment]
No, it's just applying a mathematical formula using the modulo operator. (Coincidentally, I show an example of the modulo operator in this week's videos when going over the solution to dealing cards in an alternating fashion.)

**Comment by RaulPulidoB** [comment]
I was creating my program using the If else conditionals code. But after I read the article that you post. I love that solution. Can I try to do using the mathematical formula using the Modulo operator?, or is required for this project to apply the If else conditional statements

**Comment by susanBuck** [comment]
@RaulPulidoB - You can go the math formula route if you'd like 👍

**Comment by susanBuck** [comment]
Going to go ahead and close out this thread, but will create a new post after P1 with the modulo solution/example.

**Comment by susanBuck** [comment]
Re-opening this thread now that P1 has passed to share the code for a rock paper scissors game that uses a math formula to determine the winner:

```php
<?php

# Solving RPS using a math formula
# Original source: https://therenegadecoder.com/code/rock-paper-scissors-using-modular-arithmetic/

$moves = ['rock', 'paper', 'scissors'];

$playerA = rand(0, 2);
$playerB = rand(0, 2);

if ($playerA == $playerB) {
    $winner = 'Tie';
} elseif (($playerA + 1) % 3 == $playerB) {
    $winner = 'Player B';
} else {
    $winner = 'Player A';
}
```

So succinct! :-)

**Comment by RaulPulidoB** [comment]
Wow, short and sweet!!!
