### ISSUE TITLE
Project 1 - Question about index-view.php

### ISSUE THREAD

**Issue by harrison2705** [susanBuck/e2-fall21#29]
Hi Susan, 

I'm just wondering if we do need to add "**index-view.php**" for our project 1? My game is a bit complicated and I need to display HTML text within loop and conditional statements. I am not sure how we can separate the html lines and php code into 2 files. 

For example, 
" if($playerA %2==0)  {<p> Player A is correct. Player A wins.</p> } else ...."

How can we display **<p>Player A is correct. Player A wins.</p>** in "**index-view.php**"?...Should we keep it within "index.php"  instead?

Thank you

**Comment by susanBuck** [comment]
Yes, using a view file and applying separation of concerns is an important requirement of Project 1.

In your controller file, you want to capture your results in variables, then use these variables to dictate your output in the view.

So in your example, in the controller you'd have something like:

```php
if($playerA %2==0) {
    $winner = 'player a';
}
```

Then, in your view you'd use the $winner variable to dictate your output...
```php
<?php if($winner == 'player a') { ?>
   Player A is correct. Player A wins.
<?php } ?>
```

 Note how the PHP in this view/display code is used only for display purposes. There is no logic to figure out who the winner is, it's just relying on the information already determined in the controller.

For a refresher on this revisit:
+ [Separation of concerns: What is display-related PHP code?](https://hesweb.dev/e2/notes/php/separation-of-concerns#what-is-display-related-php-code)
+ [Separation of concerns: Keep View code out of Controllers](https://hesweb.dev/e2/notes/php/separation-of-concerns#keep-view-code-out-of-controllers)
+ [Week 3, Part 5 Separation of concerns](https://www.youtube.com/embed/iIfQiuklWbM?rel=0&showinfo=0)

**Comment by harrison2705** [comment]
Thank you very much for your answer. It's clear now!
