### ISSUE TITLE
P1-War: Should I store the results of each round in an array? Or, immediately display the results? 

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#30]
**Background**
I have completed the logic of my war game, and I am working on displaying the results. I notice in the example that you give, your html table has a row for each round. Since each game has a variable number of rounds, the display table will have a variable number of rows. I was thinking about two solutions, and wondering if one would be better.

I have a while loop that plays a hand until one player has zero cards. The while loop is essentially equivalent to one round of the game. Within the while loop, I keep track of p1card, and p2card, determine the winner of the round, and then take the appropriate action with the cards. At the end of that while loop, I count cards for each player and iterate the round#. It is here that I need to display results. At that point, I could:

**Solution 1:** 
add a new row to the html table. I could display cards played, the result of the round, and the number of cards remaining for each player. The values of my variables would change once the next round takes place. 
**Solution 2:**
store each of the variables in an array. The array would have a scope outside of the while loop. The array could store all appropriate variables. Essentially, the array would be like a database of round results. After the game is completed, I would use elements from this array to display the results of each round in an html table. This would require a loop from within the index-view.php file. 

**My thoughts:**
*Solution 1* would not take up storage space. If I display the results of each round, I don't really need to access them again. No need to store them. No need to create the array. The difficulty comes from the separation of concerns. I think I could easily include the code which adds a new round to the table.

``` 
<tr>
            <td><?php echo $roundsPlayed; ?></td>
            <td><?php echo $p1Card['name']; ?> of <?php echo $p1Card['suit']; ?></td>
            <td><?php echo $p2Card['name']; ?> of <?php echo $p2Card['suit']; ?></td>
            <td><?php echo $roundWinner; ?></td>
            <td><?php echo $cardsRemainingP1; ?></td>
            <td><?php echo $cardsRemainingP2; ?></td>
 </tr>
```
The problem with this solution is how would I end my table. I would need to add this row for each round played. 
**Is there a way to send this row to the view, and then continue with my while loop in the control?**

*Solution 2* would let me run a for loop in the html part of my code. I would just do the above code for each element in the array. It seems a bit more simple,  but it comes at the cost of storing all of those pieces.

**Comment by susanBuck** [comment]
You should go with Solution #2. In the controller, gather all the results in an array, then in the view, loop through that array to display the results.

The memory to build/store the array should be negligible. I'm going to look at your other post now about running out of memory to see what's going on.

**Comment by mike32jacobs** [comment]
Thank you. I will close this post an go to the other post to keep the conversation going.
