### ISSUE TITLE
Alternate solution for Week 4 dealer example - using a for loop

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#31]
As a solution to the dealer example from Week 4, I implemented a `for loop` instead of a `foreach` loop. My logic was that since I knew how many cards there were, I could loop through them, pop one out each time, and add to the player and computer arrays. 

### My code

```php
<?php

$cards = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
shuffle($cards);

$playerCards = [];
$computerCards = [];

for($i = 0; $i < 9; $i++) {
    $playerCards[] = array_pop($cards);
    $computerCards[] = array_pop($cards);
    $i++;
}

var_dump($playerCards);
var_dump($computerCards);
```

### Example of output

```
`array(5) { 
[0]=> int(10) 
[1]=> int(6) 
[2]=> int(4) 
[3]=> int(5) 
[4]=> int(1) 
} 
array(5) { 
[0]=> int(7) 
[1]=> int(2) 
[2]=> int(9) 
[3]=> int(8) 
[4]=> int(3) 
}`
```

### What are your thoughts on this solution?
While I think my code works, let me know if you see any bugs or potential issues! I'd love to hear your thoughts.

**Comment by susanBuck** [comment]
Looks good, @ngal2021!

Only note I'd add is if you wanted to make it more flexible to handle larger/smaller decks, you could use PHP to find out your count of cards.

```php
$cardCount = count($cards);
```


Then use that in your for loop:

```php
for($i = 0; $i < $cardCount; $i++) {
    $playerCards[] = array_pop($cards);
    $computerCards[] = array_pop($cards);
    $i++;
}
```

This way if you decide to add more cards, your for loop wouldn't have to change.

Thanks for sharing. :) I think next semester I'll alter this question and challenge students to solve this problem with a foreach loop, a while loop, and a for loop. Would be good practice to try all three different approaches.

**Comment by ngal2021** [comment]
@susanBuck That's a great addition to make the code more flexible! Thank you for the feedback, I appreciate it.
