### ISSUE TITLE
Digital Ocean remote server connection issue

### ISSUE THREAD

**Issue by abarry25** [susanBuck/e2-fall21#33]
Hi all - When attempting to set up SSH Host today I am experiencing slowness and ultimately a failed attempt to connect. Anyone else having similar connectivity issues?

The setup + reconnection has been spinning for about 20 minutes before throwing up a fail message. 

![image](https://user-images.githubusercontent.com/89276236/135764322-9d4ab39d-6f81-432e-a3bb-7d0c9f32b394.png)

**Comment by susanBuck** [comment]
Hi @abarry25 - 

I'm not facing similar issues on my end. 

I don't see any pertinent issues on DigitalOcean's status board: https://status.digitalocean.com.

Just to double check - is this a host you've successfully connected to in the past and are just having problems today? Or is this your first time connecting to this host?

**Comment by abarry25** [comment]
@susanBuck I returned just now, and it seems to be resolved! For reference, it is the same host I've connected to in the past. 

Thank you for following up. 

Alexa

**Comment by susanBuck** [comment]
Glad it's resolved itself! I'll leave this thread up for another day to see if any other students report similar issues.

**Comment by ant513g** [comment]
I have also been having this issue for the past few days. It has been connecting at first, then after an hour or so, it loses connection and then attempts to reconnect. And I'm unable to disconnect while it's reconnecting. I've have to force close VSCode and restart it, but when it load up again, it still doesn't work either. But if I stop working on it and come back to it a few hours later, it seems to work. I have also been connecting to the same host.

<img width="556" alt="Screen Shot 2021-10-05 at 1 08 56 PM" src="https://user-images.githubusercontent.com/89939545/136070677-740969fd-a7bb-4e0a-9af9-5cd08d56e794.png">
