### ISSUE TITLE
Separation of concerns: Accumulating/displaying results for a multi-round game

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#34]
I had a student inquire via email the best way to display results for a multi-round game. Because this is a question others might have as well, I wanted to share the answer here in the forum.

**In summary:**
For a game with multiple rounds, you want to accumulate the results in an array in the controller. Then, in the view, you use a loop to iterate through and display those results.

[As an example of this, check out this video where I expand on the Coin Flip example to work with multiple rounds...](https://www.youtube.com/embed/xtx62XIdeUg?rel=0&showinfo=0)

**Comment by harrison2705** [comment]
Thank you so much for showing us how to display results for multi-round game!
