### ISSUE TITLE
Digital Ocean Servers down

### ISSUE THREAD

**Issue by syedyasirkamal** [susanBuck/e2-fall21#36]
As I was trying to submit and commit changes to Github

The Digital Ocean servers went down at the last minute and the sites were loading with lag.
I have attached screenshot with my VS attempting to reconnect.

![image](https://user-images.githubusercontent.com/88914181/136135819-3aaa930a-ec32-40ca-a642-7f449de18a0f.png)

**Comment by susanBuck** [comment]
It looks like your p1 is loading as of this writing on my end : http://e2p1.kamalzadeh.me/

Is it still not working for you?

**Comment by syedyasirkamal** [comment]
I cannot commit my final changes now since nothing is opening 
This is the error I am now getting when I restarted VS.

![image](https://user-images.githubusercontent.com/88914181/136136420-824496b3-4e95-4ee8-941f-e0e90b6e4f10.png)

**Comment by syedyasirkamal** [comment]
Ok it just reconnected. Thanks God!

**Comment by susanBuck** [comment]
Glad it reconnected. This is not a problem I've encountered yet, but a couple other students have noted issues (ref: https://github.com/susanBuck/e2-fall21/issues/33).

I'll be doing some research on this tomorrow to see if we can figure out why it's happening.

**Comment by susanBuck** [comment]
I just created a centralized thread (#37) to gather all the details/issues I've seen on this problem, so I'm going to go ahead and close this thread out and we can continue any discussion on this there. 

Thanks for reporting, @syedyasirkamal!
