### ISSUE TITLE
Issues with VSCode remote connection to Digital Ocean server? Read this...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#37]
Hi everyone,

There have been a few reports of students having issues when working on their servers via VSCode remote dev (ref: #36, #33, #20). I want to figure out why this is and so I'm starting this thread to try and streamline all the information we have on the matter.

**Summary of the symptoms students have reported**
+ Slow connectivity
+ Keeps showing dialog _"Reconnecting to SSH: [host name]"_
+ Stuck on _"Setting up SSH Host [host name]: Initializing VS Code..."_

**Misc notes**
+ All issues have either resolved themselves with time, or by restarting VSCode
+ Each time there's been an issue reported, I've checked DigitalOcean's status page (https://status.digitalocean.com/) and have not seen any outtages reported. Because of this I don't think it's an issue with the server itself, but just the connection/remote development setup between the server and VSCode.

**Things to do/try If you face a connectivity issue**
1. Open the [command palette](https://hesweb.dev/e2/notes/infrastructure/vscode#command-palette) and run `Remote-SSH: Show log`. This will open a log in the Output tab of the Terminal window. Share the log info in a reply to this thread.
2. Also within the command palette, run `Remote-SSH: kill VS Code Server on Host...` and see if that resolves the problem. Report back in your reply to this thread as to whether it does/does not.
3. Also in your reply, let us know the following:
    + What operating system are you using?
    + What are your download and upload speeds according to [Speedtest](https://www.speedtest.net/)?

**Comment by abarry25** [comment]
Hi all,

I am continuing to have issues with the connection. Is there a way to check our code locally? I am spending most of my time waiting for or troubleshooting the remote connection. Hoping there is a way to work through and check the code periodically while waiting for the connection solution?

**Comment by susanBuck** [comment]
Yes, I can work up some instructions for setting up a local dev environment as a substitute. 

In the interim can you try/follow-up on the 3 points listed above under "Things to do/try If you face a connectivity issue" ?

**Comment by susanBuck** [comment]
I've put together some quick instructions on setting up a local development environment:

+ Notes here: [Appendix → Local dev](https://hesweb.dev/e2/notes/infrastructure/local-dev)
+ [Video here...](https://youtu.be/St-96_e-DAs)

Ideally we can get to the bottom of the remote dev issues though, because in upcoming material we'll have to work with a package manager and a database, which are two server related things. If some students are working on a local dev server, we'll have to have a whole separate set of instructions for that and it can start to get confusing.

@abarry25 In addition to the 3 points I requested in my last reply, can you also tell me how often you're having connectivity issues. Is it 100% of the time when you're working? 50% of the time? 10% of the time? Etc.

**Comment by abarry25** [comment]
@susanBuck  Thank you for this reply! Your support is much appreciated, especially on a weekend. 

1 + 2 :  When the connection was not working, Remote-SSH: Show log + Remote-SSH: kill VS Code Server on Host... came up as not available and I wasn't able to troubleshoot  via the Command Palette.  

3. I am using a PC, Microsoft Windows. 

4. I would say about 50%-75% of the time I am having connectivity issues

Thank you!

**Comment by susanBuck** [comment]
50-75% of the time sounds extremely frustrating. Sorry you're having to deal with that!  

If it's okay with you, I'd like to connect to your server and see if I can replicate the issue on my end. 

If this is okay, [here's how to give me access...](https://hesweb.dev/e2/notes/appendix/instructor-server-access)

**Comment by susanBuck** [comment]
I did some more research on this issue tonight and have found one potential cause could be a bandwidth issue, specifically with limited upload speeds.

I purposefully throttled my network and was able to create some connectivity issues similar to the ones students have described.

As a potential fix, I completed the following two steps:

## Step 1
In your VSCode settings, search for *Remote.SSH: Connect Timeout* and increase the default value of 15 seconds to 60 seconds.

![image](https://user-images.githubusercontent.com/237711/136875206-fb6a7c1e-260e-4459-8e62-d06c2ca69cf3.png)

If it is a bandwidth issue, this will give VSCode more time to connect before it fails/timesout.

## Step 2
Open your SSH config file in VSCode by clicking the remote dev icon on the bottom left and choosing _Open SSH Configuration File_.

Update your host block for your DigitalOcean server, adding settings for _ServerAliveInterval_ and _ServerAliveCountMax_ as shown in this example: 

```
Host hes-on-DigitalOcean
  HostName your.ip.address
  User root
  ServerAliveInterval 60
  ServerAliveCountMax 10
```

This will prevent your connection from timing out once you are connected.



## Misc
+ If you're having connectivity issues, please run an [internet speed test](https://www.speedtest.net/) and include your download/upload speed results in your reply here so I can see if there is a common thread of slower network speeds.
+ This thread has many details about connectivity issues which I referenced in this post: https://github.com/microsoft/vscode-remote-release/issues/246

**Comment by susanBuck** [comment]
Hi @abarry25 (and anyone else experiencing connectivity issues) - 

Just wanted to check in on this thread, as this week (9) we'll be working with a dependency management program called Composer which I'll have you install on your servers. 

If any students were unable to solve the connectivity issues and had to go the local development route, I'll need to know this so I can provide alternative instructions for working with Composer.

**Comment by abarry25** [comment]
Hi @susanBuck,

Thank you for following up! I have not had any issues since the last follow up. Not sure if there was an issue on my end, I didn't end up changing anything about my environment. For now, it seems like it is settled for me. Sorry for the delayed response. Thank you again, 

Alexa

**Comment by mgarimelHES** [comment]
In my case, it pops up every few days if I leave my VS to connect to the  remote dev server continuously , I have to restart the server again to refresh the remote connections, otherwise the remote connection will be hanging and trying to connect forever. I am curious if there are any better approaches or best practices.  

Thanks

**Comment by DmitryBrown** [comment]
One thing I noticed is my SSH issues with VS Code went away after I upgraded my droplet ram from 512kb to 2 GB. At 512kb I had issues installing angular and running ng serve. With 2 gb ram, ssh issues went away, and ng serve now works.
