### ISSUE TITLE
How do you do your screencasts?

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#41]
I am a math teacher, and I have to make screencasts for lots of topics. I noticed that you paused the video, and had some text and an image pointing toward the screen. I am just wondering about your setup. I have used quicktime player, loom, and zoom. All of them seem to have their limitations and advantages. I am just curious about what software you use. Can you share?

I don't usually edit the videos because I often have very quick turnaround times, and I need to just be okay with mistakes.

![Screen Shot 2021-10-09 at 6 33 54 AM](https://user-images.githubusercontent.com/77531411/136654765-22da9cc0-9dcb-4224-a453-b5b9f3799463.png)

**Comment by susanBuck** [comment]
The program I use is called Screenflow. It's built for screencasting and more straightforward than a regular video editing program (e.g. Final Cut) so it's pretty easy to learn.

The pauses I sometimes put in videos isn't a special feature in Screenflow - just a combination of edits (freeze frame + pause graphic + sound effect for the pause at the start and end). 

If you do screencasting on the regular I think you'll find it a big improvement over QuickTime.

**Comment by mike32jacobs** [comment]
Thanks
