### ISSUE TITLE
Week7 - Assignment access issue

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#43]
Hello **Susan**,

I don't know if it is for me or everyone is facing the issue -  I am not able to access the *Week7 Assignment*, I am able to access the preview, but not the actual assignment. I am getting the 'Access Denied' issue -

Thanks

Murthy

**Comment by susanBuck** [comment]
Can you confirmed your logged into Canvas? I've had this happen to students in the past when they didn't realize they weren't logged in.

If you are logged in and it's still not giving you access, let me know.

**Comment by susanBuck** [comment]
Sorted this out via email with @mgarimelHES so I'm going to close this thread.

The issue was I was still linking to last semester's assignment from the lecture page. It's corrected now!

**Comment by mgarimelHES** [comment]
Thanks **Susan**

**Comment by mgarimelHES** [comment]
Hi Susan - Thank you!



Regards,

Murthy Garimella

HES - ALM
