### ISSUE TITLE
Issue creating new subdirectory within E2 repository

### ISSUE THREAD

**Issue by lyonsco** [susanBuck/e2-fall21#44]
I keep getting an error when trying to create a new subdirectory within E2. It happened when I tried to create a new p1-refactored subdirectory by copying the directory using the cp command, and also when I just tried to create a new folder for p2. Here is what I see, even though I copied my p1 files so was expecting the same output in the browser (http://e2p2.hesclyons.me/)
<img width="526" alt="Screen Shot 2021-10-18 at 1 19 54 PM" src="https://user-images.githubusercontent.com/12960522/137778573-886ab4b9-2c26-4d4a-8592-2ede1d25d5cf.png">

Has anybody had this issue? The only way I could get it to work was to create a new folder within my existing subdirectories (e.g. p1 or practice). 

Thank you!
Courtney

**Comment by susanBuck** [comment]
Hi @lyonsco -

Can you confirm you updated your `/etc/nginx/sites-available/hes` file to add a new block defining the e2p2 subdomain and which directory it should point to? 

Also, don't forget to restart nginx after making changes to this file (`systemctl restart nginx`).

If you've done those steps and your e2p2 still isn't loading, let me know.

Ref: https://hesweb.dev/e2/notes/infrastructure/subdomains

**Comment by lyonsco** [comment]
Hi @susanBuck,

Thank you for the reminder; I had forgotten those steps. It is working now. Thank you!
