### ISSUE TITLE
Useful read: Writing clean code - Naming

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#49]
This article came across my inbox last week and thought it was a useful/relevant read to our discussion of code style and design so I wanted to share:

https://www.codementor.io/@tanakamutakwa/writing-clean-code-naming-1msxn728ht

**Comment by mike32jacobs** [comment]
This made me think about my style in project 2. In particular, I wanted to know if there are times when you would find it OK to mix camelCase and snake_case. In my project, I used camelCase to name variables, but I used snake_case to name function. I know that you said we should choose one or the other, but this kind of helped me distinguish different parts of my code.

+ _**Example:**_
```
    $playerHand = [];
    $dealerHand = [];

    # Deal two cards to player, and to the dealer
    $playerHand = deal_to_player($playerHand, 2);
    $dealerHand = deal_to_player($dealerHand, 2);

    # Calculate sum of cards
    $playerTotal = calculate_total($playerHand);
    $dealerTotal = calculate_total($dealerHand);
```
+ _**Question:**_
Would you recommend a change, or do you think that this difference is logical enough that I should continue the practice?

**Comment by susanBuck** [comment]
Hi @mike32jacobs - 

I'm torn on this - I get your reasoning, but it's also not a practice I've seen on a company/project/language wide basis. Given the latter, I'm not sure it's a practice I would encourage.

I'd also note that there is already a distinguishing factor between variables and functions - variables are always prefixed with `$` and functions are always followed by `()`.

Also, typically functions involve verbs--- deal, calculate, get, etc. so that's another distinguishing factor.

One place I do mix underscores and camelCases - sometimes - is when working with databases. I work a lot with the framework Laravel and their database naming conventions for table names, field names, etc., is to use underscores. You can overwrite this, but it's easier just to stick with the convention. And - similar to the goal you had with distinguishing things - it works out nice because when I see underscores I know it's something DB related.

I don't have a hard yes/no answer on your question, so I'd say take the above into account and go with what makes the most sense to you - key thing is just that you're consistent. : )

**Comment by mgarimelHES** [comment]
I think as you mentioned earlier in the class, consistency and sticking into one pattern helps not only the developer but also in a team environment to support and maintain the code in long run.

Good info, Thanks.
