### ISSUE TITLE
Coin Flip - sample code location

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#51]
Hi **Susan**,

Could you please share the location for 'coin flip' code base, I am trying to include the images for my project2 and having some issues with them. If it is an issue, I may skip if it is too complex.

Thanks,

Murthy

**Comment by susanBuck** [comment]
Hi @mgarimelHES 

My e2 repo is at https://github.com/susanBuck/e2
The coin flip game can be found under the p2 directory: https://github.com/susanBuck/e2/tree/main/p2

**Comment by mgarimelHES** [comment]
Hi Susan,

 Thanks, it is very much appreciated.


Regards,

Murthy Garimella

HES - ALM
