### ISSUE TITLE
Issue connecting to rps subdomain

### ISSUE THREAD

**Issue by lyonsco** [susanBuck/e2-fall21#53]
I configured the rps subdomain following the steps outlined in class, and it was working a few days ago when I set it up, but now I get the following message when I try to access it in the browser (https://e2rps.hesclyons.me/): 

This site can’t be reachede2rps.hesclyons.me refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

My other subdomains are working. I tried going through the subdomain configuration steps again, and I also checked my proxy settings as it advises to see if any are checked. Do you have any other suggestions on how to resolve this?

Thank you for your help!
Courtney

**Comment by susanBuck** [comment]
Hi @lyonsco -

Use the url with just http, not https.

http://e2rps.hesclyons.me/

Because we haven't set up https, that won't function.

**Comment by lyonsco** [comment]
@susanBuck, thank you for the quick response! That is working!
