### ISSUE TITLE
Framework Installation - Missing Vendor directory - Missing extensions

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#56]
Hello **Susan**,

I am following your video about the *Framework Installation* and it looks like it did not install the *Vendor* directory as shown in your repo (missing Vendor directory)[https://github.com/susanBuck/e2/tree/main/zipfoods](url) 
Q - How can I add 'Vendor' directory and if I run command *composer install* on this project, is it ok?

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES -

Hm, that's odd - it should have installed the vendor directory for you. Can you run the create-project command again (`composer create-project --prefer-dist susanBuck/e2framework zipfoods`) and share the full output with me?

To do this you'll need to delete your existing zipfoods directory (or rename it to something else).

Note: It's expected that my zipfoods directory would _not_ show a vendor directory when looking at it on Github (https://github.com/susanBuck/e2/tree/main/zipfoods) - this is because the vendor directory is ignored via the .gitignore config file. If you haven't got to the last video yet, it'll explain why.

**Comment by mgarimelHES** [comment]
I think it is similar kind issue from last week about zip extension -
![image](https://user-images.githubusercontent.com/64241541/140243363-3ed5ed13-e4b7-48d7-ae6c-f6dcf8e402d7.png)

I have deleted the folder 'zipfoods' and ran the command *composer create-project --prefer-dist susanBuck/e2framework zipfoods* and the result is show in the above screenshot.

**Comment by mgarimelHES** [comment]
I have installed zip / unzip on my server, but the warning is gone. But still it has the problem1-

![image](https://user-images.githubusercontent.com/64241541/140247576-72a94527-b462-4c2a-8ee7-870fd57e30f3.png)

**Comment by susanBuck** [comment]
It looks like now it wants the extension `ext-mbstring`. I'm puzzled why my server had the extensions by default, but yours did not. I want to look more into this tomorrow but in the interim, instructions below for getting set up with the extensions you might need.


# Extension instructions

First - specify a new repository *apt-get* can download software packages from. The repository we’re adding is [ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/linux/php), the primary source for PHP-related packages:

```bash
sudo add-apt-repository ppa:ondrej/php
```

Next, invoke *apt-get* to get the latest packages from your apt-get repositories (including your newly added one, *ppa:ondrej/php*):

```bash
$ sudo apt-get update
```

Now that everything is updated, we’ll install the modules:
```
$ sudo apt-get install php7.4-mbstring zip unzip
```

**Comment by susanBuck** [comment]
I think I figured out what's going on. 

Earlier on I had tested installing Composer via "apt" (Linux package manager), and it appears that in addition to installing Composer it will install the extra extensions Composer will need (zip, unzip, mbstring)

But this is not how I instructed students to install Composer (there was some issues with the version it downloaded). As a result, your server's never got the necessary extensions so they need to be installed manually.

Sorry for that mixup/confusion. I'm going to update the notes with the above steps for adding the extensions, and I'll reupload the relevant videos with an edit speaking to this.

**Comment by susanBuck** [comment]
Updated notes with extensions instructions: https://hesweb.dev/e2/notes/php/composer#composer-pre-install-extensions

**Comment by mgarimelHES** [comment]
Hi **Susan**,

 Thanks for your help, the issue is resolved and I am able to see 'vendor' folder and it works as expected -
![image](https://user-images.githubusercontent.com/64241541/140257488-d3221259-7f64-4a13-8733-c0722f5ab326.png)

**Comment by mgarimelHES** [comment]
Hi Susan,

The  problem is resolved after installing the recommended packages and
following the updated notes.

Appreciate it.


Regards,

Murthy Garimella

HES - ALM

**Comment by ngal2021** [comment]
> Updated notes with extensions instructions: https://hesweb.dev/e2/notes/php/composer#composer-pre-install-extensions

@susanBuck, I am having this issue installing my framework as well. I wanted to clarify in which directory to run the _**Composer pre-install - extensions**_ commands listed in the notes, the first of which is the one below:

`$ sudo add-apt-repository ppa:ondrej/php`

Should I run the command in **/usr/bin** of my development server? Thank you!
