### ISSUE TITLE
Composer / e2framework - missing extensions

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#57]
Hi all,

There are a few extensions you'll need to install on your servers when working with Composer and the e2framework. Without them, you'll run into some errors when invoking Composer, including some of the following:

+ _Failed to download susanbuck/e2framework_
+ _zip extension and unzip/7z commands are both missing_
+ _Your requirements could not be resolved to an installable set of packages_
+ _require ext-mbstring missing_

**Getting the needed extensions installed is easy - just takes 3 commands - instructions here: https://hesweb.dev/e2/notes/php/composer#composer-pre-install-extensions**

Apologies for not mentioning these steps earlier! It was part of the instructions in previous semesters, but I took them out this semester when I mistakenly thought LEMP droplets were now coming with these extensions installed by default. (I realize now I only had them on my demo server because of some other, unrelated steps I had taken).

Related posts: #56 #52

**Comment by mike32jacobs** [comment]
Thank you. I started the E2 Week 10, Part 3 video before I saw this post. I ran into the problems you described. I just deleted the entire zipfoods folder, then followed these instructions, and then did the video over. No problems.

**Comment by lyonsco** [comment]
Same here. I similarly deleted the zipfoods folder as @mike32jacobs did, installed the extensions described above, and it is now working. Thanks!

**Comment by susanBuck** [comment]
Thanks for confirming @mike32jacobs & @lyonsco!

**Comment by gotgits** [comment]
My question is could someone share the command that will locate my /e2 directory and contents from **SSH:hes-on-DigitalOcean ** that I see under sites available in VSCode.
The reason is I also ran into issues today, and in the process of updating the hes config file and installing zipfoods which I saw with all it's contents, I have broken all of it, can't get back to my remote development folders at all now and I am at the point of a small meltdown. I am wondering how far back do I have to go if I cannot see even e2 directory anymore and will I break things even further accidentally creating a new ssh key pair. 

I have never managed remote sites only worked in them. I have gone back to the subdomains sites-enabled and everything was fine but I lost all connection in the browser, so I kept trying to locate (successful) and restart with the new framework server array  saw a list of contents in CL Terminal, everything was fine and then I just misplaced all of it. To make matters worse I have recently gotten a reply to a help desk at Namecheap from early September, but my issue was resolved and it has been working perfectly all semester so I ignored it for a couple of days. Clearly that has it's own unnecessary risks. I started checking to see if anything was browser visible, and it's not, but it was just before I moved or saved over the hes config file. So I don't actually think it's that, but they were asking for identity items, so I can't rule it out. 
So as previously stated, my question is could someone share the command that will locate my e2 directory and contents from **SSH:hes-on-DigitalOcean**  that I see under sites available in VSCode?
I would like to think it's not really a crisis, just a misstep that is compounding.
Rose

**Comment by susanBuck** [comment]
Hi @gotgits - To confirm, you are able to connect to the server, you're just trying to locate the e2 folder on the server?

If so, while connected to the server, you can run the following command in Terminal and it should open a new VSCode window that is a) connected to the server and b) showing your `e2` directory in the FIle Browser:

```
code /var/www/e2
```

If that's not working - or I'm not 100% understanding your question - just let me know and we'll go from there.

We can also connect on Zoom anytime tomorrow after 11am ET if that's at all helpful.

Regardless - try not to panic - we always have a backup of your code on Github, and the server is something that can always be recovered/straightened out.

**Comment by ngal2021** [comment]
I want to clarify in which directory to run the **_Composer pre-install - extensions_** commands. Should they be run in **/usr/bin** of my development server? Thank you!

I asked this question on a closed issue (I missed this post and thought that the other post was reopened), so I moved my question here!

**Comment by susanBuck** [comment]
Hi @ngal2021 - Good question. They can actually be run from any directory.

**Comment by ngal2021** [comment]
> Hi @ngal2021 - Good question. They can actually be run from any directory.

Thank you, @susanBuck ! I've made it to the third command on my second try, but I am facing this issue:
```
root@hes:/var/www/e2# sudo apt-get install php7.4-mbstring zip unzip php7.4-xml
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 594486 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
This is my second time trying to install extensions. When I first executed the command, it asked me to compare two different files (I saw a pink screen, and selected, compare the two files line by line). I was having a hard time accepting/making edits, and didn't understand how to exit where I was, so I ended up closing out the terminal. I think that my system might still be running the file.

**Comment by susanBuck** [comment]
Hi @ngal2021 - 

Can you follow the instructions here to give me access to your server: https://hesweb.dev/e2/notes/appendix/instructor-server-access ?

I can log in and take a look at what's going on.

**Comment by ngal2021** [comment]
@susanBuck, I ran the command, let me know if you have trouble accessing my server!

**Comment by susanBuck** [comment]
@ngal2021 - Great - checking it out now - will report back shortly!

**Comment by susanBuck** [comment]
@ngal2021 ok you should be all set now - I added the extensions for you just to get you back on track as quickly as possible.

I'll reply again soon with more details about what I did, but I just wanted to get this quick reply out there so you could proceed forward.

**Comment by susanBuck** [comment]
**Summary of what I did:**

I attempted to add the extensions, confirming I got the same error you saw: 

```
root@hes:~# sudo apt-get install php7.4-mbstring zip unzip php7.4-xml
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 594486 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

I googled some of the phrases from this error (*"Could not get lock /var/lib/dpkg/lock-frontend. It is held by process"*) and it lead me to this resource: https://itsfoss.com/could-not-get-lock-error/

There it explains the problem as follows:

> You see this error because some other program is trying to update Ubuntu. When a command or application is updating the system or installing a new software, it locks the dpkg file (Debian package manager).
> 
> This locking is done so that two processes don’t change the content at the same time as it may lead to unwarranted situation and a possible broken system.

Following the instructions that resource provided, I ran the command `ps aux | grep -i apt` to see what existing apt processes were running, and killed them all.

When I attempted to install the extensions again, I now got a different error:

```
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

Following the instructions in the prompt, I ran `sudo dpkg --configure -a`, which brought up that pink screen you were describing. From what I recall, this screen was noting some changes/conflicts in a php.ini file and was asking how we wanted to handle those changes. I choose the first option, which was effectively resetting the php.ini file.

After I did this, I was able to install the extensions with success. 

One hitch, though, was changes we had made earlier in the semester to our php.ini files was now reverted. To address this, I just revisited the instructions from the [error reporting notes](https://hesweb.dev/e2/notes/php/error-reporting#error-reporting) to reconfigure those settings.

**How did this happen?**
I can't say for sure why you ran into the hitches you did, when other students didn't. 

I did notice when I was getting the list of apt commands running there was one for `apt-get install php7.4-mbstring zip unzip php7.4-xml` without the `sudo` prefix. I'm wondering if you may have ran that command first, and it started the update process, but upon realizing you were missing `sudo` you interrupted the process? That might explain why that dpkg file was left in "limbo" so to speak. :)

Regardless of how it happened, you should be all set now - and because this was a one time thing that needed to happen, you shouldn't run into further problems (related to this at least :).

**Comment by ngal2021** [comment]
> @ngal2021 ok you should be all set now - I added the extensions for you just to get you back on track as quickly as possible.
> 
> I'll reply again soon with more details about what I did, but I just wanted to get this quick reply out there so you could proceed forward.

@susanBuck, thank you so much! I deleted my old project and created a new zipfoods project, no issues this time.

**Comment by ngal2021** [comment]
@susanBuck, thank you for walking through the steps you took to solve the problem, including the notes of the phrases you searched and the info gleaned from the resources. Very helpful steps that I can apply to other problems: detailed search terms; ensuring the info in the resource is aligned with the problems I am seeing. The missing 'sudo' command might be the culprit - I didn't notice that it was missing, but I might have interrupted the process for some other reason, maybe incorrectly thinking that the process was complete.
