### ISSUE TITLE
(UPDATED) VSCode connection issues with DigitalOcean

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#58]
Earlier in the semester I made a thread (#37) addressing connectivity issues some students were facing with VSCode and DigitalOcean.

**I have consolidated what I learned from that thread into this note set: [VSCode Connection Issues](https://hesweb.dev/e2/notes/infrastructure/vscode-connection). Start there if you're troubleshooting connection issues.**

I'm interested in hearing more from you all about this
+ Have you faced connection issues this semester? If so, about how frequently?
+ If you implemented the above fixes, did it solve the problem?

I do apologize for those that have faced connection issues. I know how frustrating it can be to have your workflow interrupted while coding.

Doing remote development is something new I've tried this semester, and it has a lot of benefits because it *greatly* reduces the amount of steps necessary to get a working development environment set up (vs. setting it up all locally on your own computer). 

However, if I can't sort out the connection issues, it's obviously not the best solution! It's because of this that I'd love to hear from you all about whether the above fixes do the trick, or if the connection issues continue to persist.

**Comment by abarry25** [comment]
Hi @susanBuck, I wanted to follow up on this with what is hopefully helpful information about my connectivity issues this semester! 

Have you faced connection issues this semester? If so, about how frequently? **Yes, about 60% of the time, I am either not able to connect to the server, or am interrupted 1/2 way through a lesson or work session. I am almost never connected for 100% of my working time**

If you implemented the above fixes, did it solve the problem? **While the server is connecting, I wasn't able to find the first 2 options, but whilst connected, I was able to implement a longer Time Out time, I have just restarted my server, and for the last 20 minutes we've been connected with no interruptions. I will report back if that solve fails.**

Thank you for your support on all this!

**Comment by susanBuck** [comment]
Thanks for the input, @abarry25! Curious to hear if the "fix" helps.

**Comment by abarry25** [comment]
For the last 24 hours - I have restarted the server 3-4 times. It works pretty consistently for a couple of hours after that, but still will cut out.

**Comment by susanBuck** [comment]
Thanks for the follow-up @abarry25! I'm glad to hear the server restart at least gets you back to a working state, but having to periodically restart is still a bummer.

Another theory I've been working on is that some students might be reaching the limits of their server's limited memory.

As a potential fix for this, we can enable "swap" memory which is explained (with instructions on how to set it up) here: https://gist.github.com/susanBuck/b9310f8f0886105008a2f6a18a18d7ae

Give that a shot and let me know if it shows any improvements/reduces the need to restart the server.

Appreciate your help/input on this issue!

**Comment by abarry25** [comment]
Hi @susanBuck - Since enabling the swap memory I haven't had any connection issues with the server (about 10 days!). It went from having to restart the server 2-3 times during a 4 hour working session, to only having to once in the last 10 days. HUGE improvement. Thank you for staying on top of this and searching for solves, moving into the final project, this is immensely helpful. Alexa

**Comment by susanBuck** [comment]
@abarry25 - Thank you for the update! I'm so glad the swap file did the trick. Really appreciate your patience and input on this matter this semester. :)

**Comment by lyonsco** [comment]
@susanBuck, I have been having a lot of connectivity issues lately with the server, like those described above, so I was thinking it is likely the memory issue. I tried to go through these steps, but I keep getting stuck on this one:
```
/swapfile   none    swap    sw    0   0
```
When I try to enter that line, it keeps saying Unknown Sequence and nothing happens. Attached is what I am seeing. Is this where I should be entering that line?
<img width="953" alt="Screen Shot 2021-12-04 at 10 01 52 AM" src="https://user-images.githubusercontent.com/12960522/144714345-494e9fde-fa39-4049-b655-397b92c6aeb5.png">
?

Thank you for your help.

**Comment by harrison2705** [comment]
I faced with more connection issues this week and it happened very frequently. Restarting the server from the Digital Ocean control panel is the easiest way to solve the issue.

**Comment by susanBuck** [comment]
@lyonsco - Can you grant me access to your server so I can take a look? Instructions to do so here: https://hesweb.dev/e2/notes/appendix/instructor-server-access

**Comment by lyonsco** [comment]
@susanBuck I just ran that command to grant access. Thank you!

**Comment by susanBuck** [comment]
@lyonsco - Great, thanks - I was able to log in, and saw the same "Unknown sequence" error you saw when trying to save changes to /etc/fstab. 

I ended up copying/pasting the contents of the /etc/fstab file on my server to your server and saved that without issue. Might just have been some errant character was in the file.

Regardless, your swap is all set up now 👍

**Comment by lyonsco** [comment]
@susanBuck Great, thank you for doing that!

**Comment by swirlyup** [comment]
> Earlier in the semester I made a thread (#37) addressing connectivity issues some students were facing with VSCode and DigitalOcean.
> 
> **I have consolidated what I learned from that thread into this note set: [VSCode Connection Issues](https://hesweb.dev/e2/notes/infrastructure/vscode-connection). Start there if you're troubleshooting connection issues.**
> 
> I'm interested in hearing more from you all about this
> 
> * Have you faced connection issues this semester? If so, about how frequently?
> * If you implemented the above fixes, did it solve the problem?
> 
> I do apologize for those that have faced connection issues. I know how frustrating it can be to have your workflow interrupted while coding.
> 
> Doing remote development is something new I've tried this semester, and it has a lot of benefits because it _greatly_ reduces the amount of steps necessary to get a working development environment set up (vs. setting it up all locally on your own computer).
> 
> However, if I can't sort out the connection issues, it's obviously not the best solution! It's because of this that I'd love to hear from you all about whether the above fixes do the trick, or if the connection issues continue to persist.

My God 
you saved me
Thx very much^^
