### ISSUE TITLE
vs code extensions / mods

### ISSUE THREAD

**Issue by owen-mcg** [susanBuck/e2-fall21#60]
Hello Susan and everybody;

I was wondering what extensions in vs code people have found useful so far. For example @susanBuck, I was wondering what you use for syntax highlighting; it's always so clear and easy to read. 

They're not so much extensions, but I've been liking using some third-party fonts. Currently I'm using one called Monoid, which I like for a variety of reasons, one of which is the code specific ligatures.

**Comment by susanBuck** [comment]
Here's a list of my extensions:
```
/Users/Susan  $ ls ~/.vscode/extensions 
aaron-bond.better-comments-2.1.0			mrmlnc.vscode-duplicate-1.2.1
amirmarmul.laravel-blade-vscode-2.0.3			ms-vscode-remote.remote-containers-0.205.1
austenc.laravel-blade-spacer-2.1.3			ms-vscode-remote.remote-ssh-0.66.0
ban.spellright-3.0.60					ms-vscode-remote.remote-ssh-edit-0.66.0
bmewburn.vscode-intelephense-client-1.7.1		ms-vscode-remote.remote-ssh-edit-0.66.1
cjhowe7.laravel-blade-1.1.2				ms-vscode-remote.remote-wsl-0.58.5
coenraads.bracket-pair-colorizer-2-0.2.1		ms-vscode-remote.vscode-remote-extensionpack-0.21.0
fosshaas.fontsize-shortcuts-1.5.0			octref.vetur-0.35.0
junstyle.php-cs-fixer-0.2.8				pkief.material-icon-theme-4.10.0
luxcium.pop-n-lock-theme-vscode-3.32.7			rifi2k.format-html-in-php-1.7.0
mdickin.markdown-shortcuts-0.12.0			shufo.vscode-blade-formatter-0.8.4
michelemelluso.code-beautifier-2.3.3			tommasov.hosts-1.2.0
mikestead.dotenv-1.0.1					tyriar.vscode-terminal-here-0.2.4
```

_RE: Syntax highlighting_ - that's all dictated by the [theme I use](https://hesweb.dev/e2/notes/infrastructure/vscode#themes). 

I think the only syntax-highlighting specific extension I have is the Blade one I mentioned in this weeks lectures ([Laravel Blade by Christian Howe](https://marketplace.visualstudio.com/items?itemName=cjhowe7.laravel-blade)).

Also curious what other favorite extensions people have. : )

**Comment by owen-mcg** [comment]
Here's my list:

`➜  ~ ls ~/.vscode/extensions
74th.monokai-charcoal-high-contrast-3.3.0
aaron-bond.better-comments-2.1.0
abusaidm.html-snippets-0.2.1
actuallyzach.jelly-language-support-1.2.2
albert.tabout-0.2.1
alexcvzz.vscode-sqlite-0.14.0
aramok.aramoks-black-1.2.10
austin.code-gnu-global-0.2.2
batisteo.vscode-django-1.6.0
bierner.markdown-preview-github-styles-0.2.0
bmewburn.vscode-intelephense-client-1.7.1
celianriboulet.webvalidator-1.2.1
davidanson.vscode-markdownlint-0.45.0
dbaeumer.vscode-eslint-2.2.2
ecmel.vscode-html-css-1.10.2
editorconfig.editorconfig-0.16.4
esbenp.prettier-vscode-9.0.0
evgeniypeshkov.syntax-highlighter-0.5.0
felixfbecker.php-debug-1.22.0
firefox-devtools.vscode-firefox-debug-2.9.5
formulahendry.auto-close-tag-0.5.13
formulahendry.auto-rename-tag-0.1.9
formulahendry.code-runner-0.11.6
github.codespaces-1.3.6
github.vscode-pull-request-github-0.32.0
hediet.vscode-drawio-1.6.2
inu1255.easy-snippet-0.6.3
jeff-hykin.better-cpp-syntax-1.15.10
junstyle.php-cs-fixer-0.2.8
kokororin.vscode-phpfmt-1.0.30
leodevbro.blockman-1.3.3
mdickin.markdown-shortcuts-0.12.0
mgmcdermott.vscode-language-babel-0.0.35
morgan-codes.morgan-codes-vscode-theme-0.0.5
ms-azuretools.vscode-docker-1.18.0
ms-python.python-2021.11.1422169775
ms-python.vscode-pylance-2021.11.1
ms-toolsai.jupyter-keymap-1.0.0
ms-vscode-remote.remote-containers-0.205.2
ms-vscode-remote.remote-ssh-0.66.1
ms-vscode-remote.remote-ssh-edit-0.66.1
ms-vscode-remote.remote-wsl-0.58.5
ms-vscode-remote.vscode-remote-extensionpack-0.21.0
ms-vscode.cpptools-1.7.1
ms-vscode.cpptools-extension-pack-1.1.0
ms-vscode.cpptools-themes-1.0.0
ms-vsliveshare.vsliveshare-1.0.5090
ms-vsliveshare.vsliveshare-audio-0.1.91
neptunedesign.vs-html-to-css-1.0.0
pkief.material-icon-theme-4.10.0
pranaygp.vscode-css-peek-4.2.0
rafmsou.nicer-high-contrast-1.0.14
samuelcolvin.jinjahtml-0.16.0
sidthesloth.html5-boilerplate-1.1.1
sirmspencer.vscode-autohide-1.0.7
sleistner.vscode-fileutils-3.4.5
streetsidesoftware.code-spell-checker-2.0.12
tabnine.tabnine-vscode-3.5.0
tombonnike.vscode-status-bar-format-toggle-3.0.0
visualstudioexptteam.vscodeintellicode-1.2.14
wmaurer.change-case-1.0.0
wmaurer.vscode-jumpy-0.3.1
xabikos.javascriptsnippets-1.8.0
yzhang.dictionary-completion-1.1.1
yzhang.markdown-all-in-one-3.4.0
`

I should probably pare it down a bit...

**Comment by owen-mcg** [comment]
Here's my list:

```
$ ls ~/.vscode/extensions
74th.monokai-charcoal-high-contrast-3.3.0
aaron-bond.better-comments-2.1.0
abusaidm.html-snippets-0.2.1
actuallyzach.jelly-language-support-1.2.2
albert.tabout-0.2.1
alexcvzz.vscode-sqlite-0.14.0
aramok.aramoks-black-1.2.10
austin.code-gnu-global-0.2.2
batisteo.vscode-django-1.6.0
bierner.markdown-preview-github-styles-0.2.0
bmewburn.vscode-intelephense-client-1.7.1
celianriboulet.webvalidator-1.2.1
davidanson.vscode-markdownlint-0.45.0
dbaeumer.vscode-eslint-2.2.2
ecmel.vscode-html-css-1.10.2
editorconfig.editorconfig-0.16.4
esbenp.prettier-vscode-9.0.0
evgeniypeshkov.syntax-highlighter-0.5.0
felixfbecker.php-debug-1.22.0
firefox-devtools.vscode-firefox-debug-2.9.5
formulahendry.auto-close-tag-0.5.13
formulahendry.auto-rename-tag-0.1.9
formulahendry.code-runner-0.11.6
github.codespaces-1.3.6
github.vscode-pull-request-github-0.32.0
hediet.vscode-drawio-1.6.2
inu1255.easy-snippet-0.6.3
jeff-hykin.better-cpp-syntax-1.15.10
junstyle.php-cs-fixer-0.2.8
kokororin.vscode-phpfmt-1.0.30
leodevbro.blockman-1.3.3
mdickin.markdown-shortcuts-0.12.0
mgmcdermott.vscode-language-babel-0.0.35
morgan-codes.morgan-codes-vscode-theme-0.0.5
ms-azuretools.vscode-docker-1.18.0
ms-python.python-2021.11.1422169775
ms-python.vscode-pylance-2021.11.1
ms-toolsai.jupyter-keymap-1.0.0
ms-vscode-remote.remote-containers-0.205.2
ms-vscode-remote.remote-ssh-0.66.1
ms-vscode-remote.remote-ssh-edit-0.66.1
ms-vscode-remote.remote-wsl-0.58.5
ms-vscode-remote.vscode-remote-extensionpack-0.21.0
ms-vscode.cpptools-1.7.1
ms-vscode.cpptools-extension-pack-1.1.0
ms-vscode.cpptools-themes-1.0.0
ms-vsliveshare.vsliveshare-1.0.5090
ms-vsliveshare.vsliveshare-audio-0.1.91
neptunedesign.vs-html-to-css-1.0.0
pkief.material-icon-theme-4.10.0
pranaygp.vscode-css-peek-4.2.0
rafmsou.nicer-high-contrast-1.0.14
samuelcolvin.jinjahtml-0.16.0
sidthesloth.html5-boilerplate-1.1.1
sirmspencer.vscode-autohide-1.0.7
sleistner.vscode-fileutils-3.4.5
streetsidesoftware.code-spell-checker-2.0.12
tabnine.tabnine-vscode-3.5.0
tombonnike.vscode-status-bar-format-toggle-3.0.0
visualstudioexptteam.vscodeintellicode-1.2.14
wmaurer.change-case-1.0.0
wmaurer.vscode-jumpy-0.3.1
xabikos.javascriptsnippets-1.8.0
yzhang.dictionary-completion-1.1.1
yzhang.markdown-all-in-one-3.4.0
```

I should probably pare it down a bit... Got a little extension happy in the beginning, and the list has only grown.

**Comment by susanBuck** [comment]
@owen-mcg How many of these extensions do you also have enabled on the server? I'm wondering if this could explain why your server connection is more fickle than mine - all the extra extensions it's running?

**Comment by owen-mcg** [comment]
Hmm good question; I’d estimate about half are active. I also should say that the server is running a lot better for me. It was already doing better after your troubleshooting, but with the swap file enabled, I had zero problems. I was on there for hours yesterday, with no disconnect notices or reloads! It was amazing.

**Comment by susanBuck** [comment]
I'm so glad to hear the swap file has made things so much better! :-)
