### ISSUE TITLE
Overwriting parent Controller's construct

### ISSUE THREAD

**Issue by gotgits** [susanBuck/e2-fall21#61]
## Overwriting parent Controller's construct

I have run into an error:
```
Fatal error: Uncaught Error: Call to undefined method App\Controllers\ProductsController::missing() in /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php:225 Stack trace: #0 /var/www/e2/zipfoods/public/index.php(15): E2\App->route() #1 {main} thrown in /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php on line 225
```

I tried the simplest approach first with creating the views/products/missing in a new file missing.blade.php

That returned blank pages and seemed to effect the other previously working products/index.blade.php and the individual product pages because of routing, then I got to the point where those were also working but not the missing page that returns the above error.

I saw a __construct on the Products class that seemed like the logical place and I added
```php
public function __construct($app)
{
	parent::__construct($app);
	$missing = array_search($sku, getById($this->missing, 'sku', 'id'));
        return $this->redirect('products/missing');
}
```
I knew an issue will arise with my array search, because I need to search null for id and sku and I wanted to ask about that...

However the issue I receive this error first
**Fatal error: Cannot redeclare App\Products::__construct() in /var/www/e2/zipfoods/app/Products.php on line 17**
which breaks everything again.

this is the code I have added on routes.php
```php
   '/product' => ['ProductsController', 'missing']
   ```

   I have adjusted the ProductsController.php from ```errors/404``` to

```php
          if (is_null($product)) {
            return $this->app->view('products/missing', ['missing'=>$missing]);
            
        }
  ```
and I have returned the code to this which I began with:
```php
        if (is_null($product)){
        	return $this->app->view('products/missing');
        }
```
This gives me the same **Fatal error: ...** on the product page as well, but I thought best to start back at the beginning and comment out my trials.

[http://e2zipfoods.metrognome.me/product?sku=nestle-toll-house-cookie-dough](http://e2zipfoods.metrognome.me/product?sku=nestle-toll-house-cookie-dough)
[https://github.com/gotgits/e2/blob/main/zipfoods/app/Products.php](https://github.com/gotgits/e2/blob/main/zipfoods/app/Products.php)
[https://github.com/gotgits/e2/blob/main/zipfoods/app/Controllers/ProductsController.php](https://github.com/gotgits/e2/blob/main/zipfoods/app/Controllers/ProductsController.php)

**Comment by mgarimelHES** [comment]
I have followed the week 11 lectures (ex- error 404) and able to run 'missing' sku page. you may check out week11-part4 around 12mt into the video for some pointers??

**Comment by gotgits** [comment]
well, I can make it work, but not where I thought it was meant to work.

**Comment by susanBuck** [comment]
Hi @gotgits -

It sounds like you got it working, but a few notes to try and help clarify if things are still unclear:

1. You can't have more than one `__construct` method in a class (per the error, *Fatal error: Cannot redeclare App\Products::__construct()*). 

2. You don't need need to modify `app/Product.php` to tackle this task. 

3. You also don't need to modify the `/product` route.

All you should need to do is update the _show_ method in ProductsController.php so it checks if $product is null, and if it is, it returns your "missing" view. (I think based on what you wrote this was the correct solution you landed on):

```php
if (is_null($product)){
    return $this->app->view('products/missing');
}
```

Let me know if I can help clarify anything further.
