### ISSUE TITLE
Week13 - Console parameters

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#68]
Hi **Susan**

In week 13, under console concepts - How do we know the number of arguments required based on this syntax -
 # Invoke console
echo $app->console($argv); 

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES -

_$argv_ is a predefined variable that contains an array of all the arguments passed to a script/file when running it from command line. Ref: https://www.php.net/manual/en/reserved.variables.argv.php

The first element in this array is always the name of the script/file itself.

So if we run something like `php console App foo`, the _$argv_ array would look like this:

```
array(3) {
  [0]=>
  string(7) "console"
  [1]=>
  string(3) "App"
  [2]=>
  string(4) "test"
}
```

Here's the source of the $app->console method so you can see what it does with the arguments:


```php
/**
 *
 */
public function console($args)
{
    # Parse arguments
    $commandName = $args[1];
    $method = $args[2];

    # Set up command
    $commandName = "App\Commands\\".$commandName."Command";
    $command = new $commandName($this);

    dump("Executing $commandName@$method");

    # Execute
    return $command->$method();
}
```

Ref: https://github.com/susanBuck/e2core/blob/master/src/App.php#L73

**Comment by mgarimelHES** [comment]
Hi **Susan**,

 Thanks for a great explanation and providing the links for further info, it is very helpful.

Thanks
