### ISSUE TITLE
Q - alphaNumericDash validation error

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#69]
Hello **Susan**

I have modified my code to use the 'alphaNumericDash' as mentioned in the week14 Housekeeping session. It is working fine when I remove this condition, I am getting the following error while using it -

 
![image](https://user-images.githubusercontent.com/64241541/144314866-1add50f1-9d95-4826-ba46-143cbc9e5232.png)

Q - Do I need to update the framework code to resolve this?

Thanks

**Comment by AbdellGautier** [comment]
Hi @mgarimelHES!

I checked your repo and it looks great. I was able to replicate your issue on my end.

### **Where is the issue?**

1. Open the following file:
	zipfoods/vendor/susanbuck/e2core/src/Validate.php

2. Notice that Susan has a validate() method that extracts the validations you placed in your ProductsController.php > validate() (line 194)

3. However, your zipfoods/vendor/susanbuck/e2core/src/Validate.php does not have that method (alphaNumericDash), which indicate that you have an older package.

### **How to fix the issue?**

1. In your terminal, make sure you are in the zipfoods folder

2. Run:    composer update

3. You will notice a line like, "Upgrading susanbuck/e2core (0.1.11 => 0.1.13): Extracting archive"

4. Go back to zipfoods/vendor/susanbuck/e2core/src/Validate.php and notice that now you have the alphaNumericDash function

5. Your code should work now

Let me know if these steps were clear, and if you are able to see your code working fine now =)

Best regards,

Abdell

**Comment by susanBuck** [comment]
Great reply, @AbdellGautier! 

If that doesn't fix things, let us know @mgarimelHES.

**Comment by mgarimelHES** [comment]
Hi @AbdellGautier - Thanks for confirming my solution and providing detailed information. I might have missed this update in the lectures or something missing.

Thanks

**Comment by susanBuck** [comment]
Just in case anyone else runs into this same problem, discussion of this new validation method and running `composer update` can be found in the [Week 13, Part 1](https://www.youtube.com/embed/C-F9OT39AAo?rel=0&showinfo=0) video.

At the 7:10 mark I start talking about the new validation rule, _alphaNumericDash_.
At the 8:16 mark I talk about running `composer update` to be able to use this rule since it was a new addition to the framework.
