### ISSUE TITLE
Redirect issue - Warning: Header may not contain more than a single header

### ISSUE THREAD

**Issue by syedyasirkamal** [susanBuck/e2-fall21#71]
I keep getting the error
Warning: Header may not contain more than a single header, new line detected in /var/www/e2/p3/vendor/susanbuck/e2core/src/App.php on line 203

on my redirect method
 return $this->app->redirect('/save?round=' . $roundnum
        );

I don't know how to fix this

**Comment by syedyasirkamal** [comment]
Resolved

**Comment by susanBuck** [comment]
FYI for anyone else reading this/facing the same problem - make sure no output is sent to the page before trying to do a redirect. This includes any dump statements (var_dump, dd, dump) etc.
