### ISSUE TITLE
seeds/migration and commands in project 3

### ISSUE THREAD

**Issue by syedyasirkamal** [susanBuck/e2-fall21#73]
In which context do you expect us to integrate seeds/migration and commands into project 3?

Do you just want us to define public functions to clear out tables?

**Comment by susanBuck** [comment]
Just like I showed in lecture/the notes - migrations to create the tables your app needs, seeds to fill them with sample data. I'll show another example in this week's upcoming lecture when I review the p3 specifications.

**Comment by syedyasirkamal** [comment]
Ok but do you expect us to drop those tables before submitting the project such that the game history is blank when you see it?

**Comment by susanBuck** [comment]
Hi @syedyasirkamal - It's really up to you, but I'd leave them in a "seeded" state.
