### ISSUE TITLE
Deciphering error message - re-doing last week's exercise

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#74]
I am re-doing the exercise from last week's assignment, going along with the video. I have come across an error that I am not sure how to mitigate. Appreciative of the support in deciphering what the error message means!

### The error
It looks like there is an issue with `'sku' => $sku,` in the return statement of new().

**Fatal error:** Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/e2/zipfoods/cache/e7f22d34ceda7633367ed5ffc01e069812e9b122.php:23 Stack trace: #0 /var/www/e2/zipfoods/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath() #1 /var/www/e2/zipfoods/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get() #2 /var/www/e2/zipfoods/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents() #3 /var/www/e2/zipfoods/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents() #4 /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(293): Illuminate\View\View->render() #5 **/var/www/e2/zipfoods/app/Controllers/ProductsController.php(86): E2\App->view() #6** /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(229): App\Controllers\ProductsController->new() #7 /var/www/e2/zipfoods/public/index.php(15): E2\App->route() # 8 {main} Next ErrorE in /var/www/e2/zipfoods/cache/e7f22d34ceda7633367ed5ffc01e069812e9b122.php on line 23

### new function from my ProductsController

```php
    public function new()
    {
        $productSaved = $this->app->old('productSaved');
        $sku = $this->app->old('sku');

        return $this->app->view('products/new', [
            'productSaved' => $productSaved,
            'sku' => $sku,
        ]);
    }
```

###  Routes

```php
return [
    # Ex: The path `/` will trigger the `index` method within the `AppController`
    '/' => ['AppController', 'index'],
    '/contact' =>['AppController', 'contact'],
    '/about' =>['AppController', 'about'],
    '/products' =>['ProductsController', 'index'],
    '/product' =>['ProductsController', 'show'],
    '/products/save-review' => ['ProductsController', 'saveReview'],
    '/products/new' => ['ProductsController', 'new'],
    '/products/save' => ['ProductsController', 'save'],
    '/practice' => ['AppController', 'practice']
];
```

**Comment by ngal2021** [comment]
In my VSCode, there is a pop-up with more information, which I think might be pointing to my index.php file.

### The pop-up error message

_Parse Error : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ';' on line 1 > 1 | <?php echo $app=>old('name') ?> | ^_

### index.php

```php
<?php
# This is the main controller
# All traffic should route through here

# Define constants
define('DOC_ROOT', $_SERVER['DOCUMENT_ROOT'].'/../');

# Initialize Composer autoloading
require DOC_ROOT.'/vendor/autoload.php';

# Initialize App object
$app = new E2\App();

# Invoke router
echo $app->route();
```

**Comment by susanBuck** [comment]
Hi @ngal2021 -

The error is referencing a cache file, so that leads me to believe the problem is in a view file ([ref](https://hesweb.dev/e2/notes/php/e2framework/views#caching-and-debugging-views)).

I took a look at your products/new.blade.php file and see the syntax issue. Lines like this:

```php
{{ $app=>old('name') }}
```

Should be:

```php
{{ $app->old('name') }}
```

Change those and see if that resolves the problem.

**Comment by ngal2021** [comment]
Thank you, @susanBuck! That resolved the problem.
