### ISSUE TITLE
Code testing in the real world

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#75]
Code testing is very interesting! On web application development teams, are there typically programmers who focus solely on writing test code? 

I can see the benefit of having a team member dedicated to this, as it involves writing code in different languages (switching between php and html, especially adding in the 'test' attributes.). The person conducting tests might also have less bias around their expectations of how the code should function, as opposed to the person who wrote the controller code. For example, if I write code and include what I consider a non-complex function in my controller, I might be more willing to omit it from my tests, assuming it's something that will always work. On the flip side, I see the benefit of the main developer writing these tests - since they most likely know their code the best!

**Comment by susanBuck** [comment]
Larger companies may have developers devoted to quality assurance/testing, especially if you're doing a broad range of testing types.

That being said, there's a practice of TDD - or Test Driven Development - where testing is very much an integral part of the development process. 

When doing TDD, you'll often start a feature by writing a test for it, which effectively outlines the expectations of the feature. Then, you write the code for the feature itself with the intention of making that test pass.

It's the opposite of what we did where we wrote the feature first, then wrote the test to confirm it was working.

You raise some interesting points about how we can have a lot of bias in our code!
