### ISSUE TITLE
Faker and game with multiple attempts

### ISSUE THREAD

**Issue by syedyasirkamal** [susanBuck/e2-fall21#76]
I don't know how can we insert faker data into a game with multiple attempts for the same game.

I was successfully able to set up the number guessing game up as it should be with 4 attempts for each game. If you manually play the game, it works fine. The attempted numbers are displayed as a string. 

But I am unable to seed dummy data using faker for games with multiple attempts. Right now, the dummy data will only play one time per game regardless of outcome when it should be 4 times if the user guesses incorrectly. 

Here is the link to my game:
http://e2p3.kamalzadeh.me/

**Comment by susanBuck** [comment]
I think your issue is you're trying to simulate the game play when seeding, when instead you just need to simulate final outcomes.

Something like this:

```php
# Come up with a random array of numbers for the guesses
$guesses = range(1, 10);
shuffle($guesses);

# Randomly decide the game outcome
$outcome = ['won', 'lost'][rand(0, 1)];

# Lost
if ($outcome == 'lost') {
    
    # If the outcome is lost, we exhausted 4 guesses
    # So that's how many numbers we'll extract from our guesses array
    $guesses = array_slice($guesses, 0, 4);
    
    # Come up with a winning number that is not in our array of guesses
    $number = rand(1, 10);
    while (in_array($number, $guesses)) {
        $number = rand(1, 10);
    }

    # The "last guess" should be the last number in our array of guesses
    $guess = $guesses[count($guesses) - 1];

    # If they lost, the counter got to 0
    $counter = 0;
# Won
} else {
    
    # Randomly decide how many tries it took to guess the correct answer
    $counter = rand(1, 4);

    # Extract that many guesses from our guesses array
    $guesses = array_slice($guesses, 0, $counter);

    # The winning number should be the last number in our guesses
    $number = $guesses[count($guesses) - 1];

    # Last guess and number will match since they won
    $guess = $number;

    # Counter is tracked as "guesses left" not "guesses taken" so make that conversion here
    $counter = 4 - $counter;
}

# Convert guesses array into a string, where each number is separated by a space
$guesses = implode(' ', $guesses);

$dummyData = [
    'guess' => $guess,
    'roundnum' => $faker->sha1(),
    'number' => $number,
    'guesses' => $guesses,
    'counter' => $counter,
];
```

That's the round for one seed - you'd want to repeat it via a loop for how many rounds you wanted to seed.

FYI You don't need to require the autoload file as you're doing in [AppCommand on line 39](https://github.com/syedyasirkamal/e2/blob/main/p3/app/Commands/AppCommand.php#L39) - autoloading is set up by the framework.

**Comment by syedyasirkamal** [comment]
Ok . Yes I think i was trying to simulate the game via seeding.
