### ISSUE TITLE
Database Connection Refused

### ISSUE THREAD

**Issue by syedyasirkamal** [susanBuck/e2-fall21#77]
My game was working perfectly fine. I was in the process of implementing testing.
But now I am getting this error out of nowhere everytime i try to interact with the datatbase via the game

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/e2/p3/vendor/susanbuck/e2core/src/Database.php:22 Stack trace: #0 /var/www/e2/p3/vendor/susanbuck/e2core/src/App.php(106): E2\Database->__construct() #1 /var/www/e2/p3/app/Controllers/AppController.php(102): E2\App->db() #2 /var/www/e2/p3/vendor/susanbuck/e2core/src/App.php(229): App\Controllers\AppController->historyshow() #3 /var/www/e2/p3/public/index.php(15): E2\App->route() #4 {main} thrown in /var/www/e2/p3/vendor/susanbuck/e2core/src/Database.php on line 22

Its giving the same error via the terminal as well:

root@hes:/var/www/e2/p3# mysql -u hes -p
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
root@hes:/var/www/e2/p3#

**Comment by syedyasirkamal** [comment]
RESOLVED
This was very strange. If anyone experiences this issue, simply use the command 
sudo service mysql start

**Comment by susanBuck** [comment]
It's possible mysql is getting shut down if the server runs out of memory. 

If you haven't already, try enabling the swap file described here: 
https://hesweb.dev/e2/notes/infrastructure/vscode-connection#step-3-enable-swap-file

That could help if this happens frequently.
