### ISSUE TITLE
Database design with multidimensional arrays: multiple tables or one?

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#79]
I am in the opening stages of creating a blackjack game. I would like some help making a decision about database design.

I would like to keep track of the following for each game:
Game
+ id - autoincrementing PK
+ playerChoices - array of hits or stays-
+ playerHand - Array of Cards
+ DealerChoices -array of hits or stays
+ dealerHand -Array of Cards
+ Won - boolean (1/0) tinyint
+ Timestamp - timestamp 

Should I think of this as one table or many which can be joined?
Players: (This may seem unnecessary because I only have the dealer and the player. It would be useful if I had multiple players)
+ id autoincrementing
+ Dealer or Player 

game
+ id - autoincrementing PK
+ start time
+ Players: player_ids (This would be an array of player-ids)
+ choices_id
+ cards

Choices:
+ id - autoincrementing PK
+ player_id
+ game_id
+ choice

I know that this is early in the process, but I think it would be good for me to think about now, so I will have a clear idea on how to get game results from the database. Any resources you have that might help me clarify my thinking would be helpful.

**Comment by susanBuck** [comment]
You could go either way.

For relational databases, it's often best to avoid storing multiple bits of information in a single column - it's better to break that data out into its own table. This gives you more flexibility with the data when it comes to querying against it. 

But, for a simple app like this, it wouldn't be terrible to compact things into one table.

I'd say go with the option that feels the most logical/doable to you from a coding standpoint.

**Comment by mike32jacobs** [comment]
Thank you. I am going to try using more than one table.
