### ISSUE TITLE
p3 - Invoking another method from a method

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#80]
Hi,

 I am trying invoke a method 'processB' from method 'processA' within a same controller 'AppController.php'. But I am getting the error as follows -
"Fatal error: Uncaught Error: Call to undefined function App\Controllers\processB' 

 It was working fine when I do similar functionality in project2, but it complains in the framework?

Any thoughts?

Thanks

**Comment by susanBuck** [comment]
Can you update your repository with the latest code?

**Comment by mgarimelHES** [comment]
IThanks, I have uploaded the latest to the repository. It is in
work-in-progress.


Regards,

Murthy Garimella

HES - ALM

**Comment by susanBuck** [comment]
When invoking one method from another method within the same class, you have to use the _$this_ keyword.

For example, in your [AppController.php on line 39](https://github.com/mgarimelHES/e2/blob/main/p3/app/Controllers/AppController.php#L39):

```php
$winner = callMe();
```

Should be:

```php
$winner = $this->callMe();
```

Ref: https://hesweb.dev/e2/notes/php/oop#the-basics

> In the getAll method we used a special pseudo-variable called $this which references the current object instance of the class.

In the example in the notes, it's referencing a parameter, but the same rule applies with methods.

An example can be seen in ZipFoods - [the fresh method in AppCommands.php](https://github.com/susanBuck/e2/blob/main/zipfoods/app/Commands/AppCommand.php#L15) invokes other methods from within the same class.

**Comment by mgarimelHES** [comment]
Hi Susan,

 My bad, I have missed this part. Thanks for looking into it and helping me
out.

Regards,

Murthy Garimella

HES - ALM
