### ISSUE TITLE
Vertical scaling of remote development server

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#82]
Hi,

 I am not sure if anyone has tried or is it something we can try very late in the semester - I am noticing a couple of issues with the remote dev server -

1. Taking forever to connect and 'load' the remote dev server - it could be memory issue to load the complete repo from remote or network bandwidth issue.
2. Is it possible to add more resources to the remote server (ex- Memory or CPU) to resolve some of the latency / performance issues or very slow throughput?
Thanks

**Comment by susanBuck** [comment]
If you go into your Droplet settings in DigitalOcean, there's a "resize" option that allows you to upgrade resources.

Before you do that though, if you haven't already, enable a swap file ([notes here...](https://hesweb.dev/e2/notes/infrastructure/vscode-connection#step-3-enable-swap-file)). It may rectify the issue (assuming it's not a bandwidth issue).

**Comment by mgarimelHES** [comment]
Hi **Susan**

 Thanks, it is helpful and could see the improvement. I think last time I forgot the last step of editing the '/etc/fstab'.
Regards,
