### ISSUE TITLE
Error during redirect...

### ISSUE THREAD

**Issue by mike32jacobs** [susanBuck/e2-fall21#83]
I am encountering the following error, when I try to redirect from one AppController function to another.

Warning: Cannot modify header information - headers already sent by (output started at /var/www/e2/p3/vendor/symfony/var-dumper/Dumper/AbstractDumper.php:182) in /var/www/e2/p3/vendor/susanbuck/e2core/src/App.php on line 203

I am not sure how to fix it. I believe that the problem is happening as part of the redirect.

```php
        return $this->app->redirect('play',[
            'total'=>$this->total,
            'winning_score'=>$this->winning_score,
            'max_count'=>$this->max_count
        ]);
```
The function changes the value of three global variables, and then calls another function, "play", which needs access to those variables. 
Any insight would be appreciated.

**Comment by susanBuck** [comment]
Do you have any sort of output before the redirect? Via a var_dump or dump or dd function?

There can be no output to the page before doing a redirect.

**Comment by mike32jacobs** [comment]
Yes, initialize function is below: The ouput is below that:

```php
public function initialize()
    {
        // Get user input from form
        $number = $this->app->input('winning-number');
        $count = $this->app->input('max-count');

        // dump($number, $count);

        //By default, the game is played to 21, with an ability to advance by 1 or 2. .

        if ($number == null){
            $number=21;
        }
        if ($count == null){
            $count=2;
        }


        // Set global variable to values from the unser input
        $this->total = 0;
        $this->winning_score=$number;
        $this->max_count=$count; 

        dump($this->total);
        dump($this->winning_score);
        dump($this->max_count);
        
        //TODO: persist these results to database. Then let the play continue.
        //TODO: Change the value of the global variables

        dump("you are inside of the initialize function");

        // return $this->app->view('play');

        return $this->app->redirect('play',[
            'total'=>$this->total,
            'winning_score'=>$this->winning_score,
            'max_count'=>$this->max_count
        ]);

    }
```

here is a screen shot of my output:

![output](https://user-images.githubusercontent.com/77531411/145680118-7b2e8f26-7090-468e-b030-fe3ff73e2939.png)

**Comment by susanBuck** [comment]
You need to remove those dump statements in order for the redirect to work. There can be no output to the page before doing a redirect.

**Comment by mike32jacobs** [comment]
Thank you.
