### ISSUE TITLE
Module Assets not found or loaded - Testing Error

### ISSUE THREAD

**Issue by abarry25** [susanBuck/e2-fall21#85]
Hi @susanBuck - Happy Sunday!

When attempting to build out my tests for the final component of the project. I encountered an error. I was able to setup Codeception and build the P3Cest.php. When I attempt to test my first simple tests, I am seeing this error, and after searching the internet, I am not sure how to solve the issue. 

[](https://github.com/abarry25/e2/tree/main/p3/tests )

<img width="450" alt="testing aerror message" src="https://user-images.githubusercontent.com/89276236/145744930-4d7423d6-2fae-417d-80f3-ad2ab5696dcc.PNG">

**Comment by abarry25** [comment]
I solved this!

**Comment by susanBuck** [comment]
How did you solve it? Might be useful info if someone else has the same problem. : )

**Comment by abarry25** [comment]
It was a typo on my end! I had input "assets" into acceptance.suite.yml not "asserts" - I got confused with the similar terms!
