### ISSUE TITLE
PHP code spotted? Course evaluations powered by PHP

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#87]
After completing my course evaluation, I noticed syntax around a hyperlink/string that reminded me of PHP. I wonder if the evaluations are powered by PHP or if there is another language that uses $ syntax.

### $($ Please click.... $)$

![course evaluation](https://user-images.githubusercontent.com/86396684/146028496-7854944f-24c4-4af9-9156-6032d19cc2e0.png)

If anyone sees the same output when completing their evaluation, it would be interesting to see what the html code looks like for the page.

**Comment by AbdellGautier** [comment]
Hi @ngal2021,

I noticed the same on my end.  Upon a quick check just now I can see two things:

- The URL reflects an .aspx extension on the pages
- There is a hidden input around line 33 where it shows a ViewState hashed value

Based on these two components I can say with confidence that it is **ASP.NET** in the back-end.

**Comment by ngal2021** [comment]
Hi @AbdellGautier,
Very interesting, thank you for looking into it!

**Comment by susanBuck** [comment]
Interesting catch, @ngal2021 & @AbdellGautier!
